# Generated by Django 5.0.3 on 2025-01-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_news_content_alter_news_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='news_images/default.jpeg', upload_to='news_images/'),
        ),
    ]
