# Generated by Django 5.0.3 on 2025-01-21 08:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
