# Generated by Django 5.0.3 on 2025-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_news_news_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_cate',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_title',
        ),
        migrations.AddField(
            model_name='news',
            name='Seo_Description',
            field=models.TextField(default='description', max_length=2000),
        ),
        migrations.AddField(
            model_name='news',
            name='Seo_Keyword',
            field=models.CharField(default='keyword', max_length=1000),
        ),
        migrations.AddField(
            model_name='news',
            name='Seo_Title',
            field=models.CharField(default='title', max_length=1000),
        ),
        migrations.AddField(
            model_name='news',
            name='Title',
            field=models.TextField(default='title', max_length=1000),
        ),
    ]
