# Generated by Django 5.0.3 on 2025-01-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_news_content_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Seo_Description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='news',
            name='Seo_Keyword',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='Seo_Title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
