# Generated by Django 5.0.3 on 2025-01-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_news_seo_description_alter_news_seo_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Slug',
            field=models.SlugField(blank=True, max_length=1000, unique=True),
        ),
    ]
