# Generated by Django 5.0.3 on 2025-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Slug',
            field=models.SlugField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
