# Generated by Django 5.0.3 on 2025-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_news_slug_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Slug',
            field=models.SlugField(blank=True, editable=False, max_length=1000),
        ),
    ]
